// Copies the self-hosted fonts and generates the icon sprite source from pinned dev dependencies.
// Run after changing either list: `node scripts/vendor-assets.mjs`. Output is committed, so the
// runtime (local server and Vercel) never depends on these packages.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const modules = path.join(root, 'node_modules');

const fonts = [
  ['@fontsource-variable/overpass/files/overpass-latin-wght-normal.woff2', 'overpass-latin-wght.woff2'],
  ['@fontsource-variable/overpass-mono/files/overpass-mono-latin-wght-normal.woff2', 'overpass-mono-latin-wght.woff2'],
];
await fs.mkdir(path.join(root, 'public/fonts'), {recursive: true});
for (const [from, to] of fonts) await fs.copyFile(path.join(modules, from), path.join(root, 'public/fonts', to));
await fs.writeFile(path.join(root, 'public/fonts/LICENSE.txt'),
  'Overpass and Overpass Mono, copyright 2016 Delve Withrington / Red Hat, Inc.\n' +
  'Licensed under the SIL Open Font License 1.1 (https://openfontlicense.org).\n' +
  'Files copied from @fontsource-variable/overpass@5.3.0 and @fontsource-variable/overpass-mono@5.3.0 (Latin subset, variable weight).\n');

const icons = {
  search: 'magnifying-glass', close: 'x', external: 'arrow-up-right', next: 'arrow-right', back: 'arrow-left',
  sun: 'sun', moon: 'moon', shuffle: 'shuffle', info: 'info', 'x-logo': 'x-logo', instagram: 'instagram-logo',
};
const symbols = [];
for (const [id, name] of Object.entries(icons)) {
  const [weight, base] = name.includes('/') ? name.split('/') : ['bold', name];
  const svg = await fs.readFile(path.join(modules, `@phosphor-icons/core/assets/${weight}/${base}-${weight}.svg`), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
  symbols.push(`  ${JSON.stringify(id)}: ${JSON.stringify(inner)}`);
}
await fs.writeFile(path.join(root, 'lib/icons.mjs'),
  '// Generated by scripts/vendor-assets.mjs from @phosphor-icons/core@2.1.1 (bold weight; MIT licence).\n' +
  '// One icon family: do not hand-edit paths.\n' +
  `export const iconPaths = {\n${symbols.join(',\n')}\n};\n` +
  'export const iconSprite = () => `<svg xmlns="http://www.w3.org/2000/svg" hidden>${Object.entries(iconPaths).map(([id, body]) => `<symbol id="i-${id}" viewBox="0 0 256 256">${body}</symbol>`).join(\'\')}</svg>`;\n');
console.log(`Vendored ${fonts.length} fonts and ${symbols.length} icons.`);
